# Built with Jekyll 3.2.0

# Setup
title:               Fugitive Verses
tagline:             'Popular Reprinted Poetry from Nineteenth Century Newspapers'
description:         'This project presents transcribed, lightly-encoded editions of poems widely reprinted in nineteenth-century US, UK, and Australian newspapers as discovered through the <a href="http://viraltexts.org" target="_blank">Viral Texts Project</a> at Northeastern University. For more information about the selection, transcription, or other aspects of these poems <a href="http://fugitiverses.viraltexts.org/about.html" target="_blank">see the edition about page</a>.'
url:                 'http://fugitiverses.viraltexts.org'
baseurl:             'http://fugitiverses.viraltexts.org'

# About/contact
author:
  name:              Ryan Cordell
  url:               https://ryancordell.org
  email:             r.cordell@northeastern.edu

# Permalinks

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme: 

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."


