# Built with Jekyll 3.2.0

# Setup
title:               Fugitive Verses
tagline:             'Popular Reprinted Poetry from Nineteenth Century Newspapers'
description:         'Fugitive Verses presents transcribed, lightly-encoded editions of poems widely reprinted in nineteenth-century newspapers.'
url:                 'http://ryancordell.org'
baseurl:             '/FugitiveVerses'

# About/contact
author:
  name:              Ryan Cordell
  url:               https://ryancordell.org
  email:             r.cordell@northeastern.edu

# Permalinks

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme: 

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."


